app = "volleyball-legends-bot-discord"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]

  protocol = "tcp"

  [services.concurrency]
    hard_limit = 50
    soft_limit = 20
    type = "connections"

  # ---- Healthchecks ----
  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    method = "get"
    path = "/"
    protocol = "http"

  [[services.process_checks]]
    command = "node"
    args = ["src/indexV2.js"]
    interval = "30s"
    timeout = "3s"
    grace_period = "10s"

# ---- Scale to FREE tier ----
[deploy]
  strategy = "rolling"

[vm]
  size = "shared-cpu-1x"
  memory = "256mb"
